### ISSUE TITLE
Roadmap (0.4 and beyond)

### ISSUE THREAD

**Issue by gbj** [leptos-rs/leptos#1147]
(This supersedes the roadmap in #501.)

# Roadmap

## Goals for `0.4.0`
- [x] Axum `extract` function (#1093)
- [x] Improvements to `<For/>` algorithm (#533, #1146)
- [x] Remove need to explicitly call `::register()` on server functions (~~#613~~, #1154)
- [x] Consider using `anyhow` in `<ErrorBoundary/>` and friends (#1228)
- [x] Support generics in multiple positions in components (#949, #1023, #1109)
- [x] **Breaking**: Reorganize features so that `nightly` is an opt-in feature and `stable` is default (#1007, #1227)

## Goals for `0.5.0`
- [x] **Breaking** Changing reactive ownership model to avoid manual use of `Scope` and `cx` everywhere (#802, #918)
- [x] (?) **Breaking**: Use new `bind:` syntax for typed children on `<For/>` and possibly other control-flow components, when useful (#1140)

# Non-breaking improvements
- [ ] Reduce number of hydration keys and component comment markers  (#972, #903)

# Goals for Future
- [x] Exploring partial hydration/server components/islands architectures that would allow us to reduce the amount of WASM shipped to the client and increase the ergonomics of loading server-only async data
- [ ] `Send/Sync` reactive system to improve ergonomics (and possibly performance) of Axum integration (#832)

# Ongoing work with no breaking changes
- [x] Website.
- [x] Completing the guide/book.
- [x] Adding end-to-end testing for examples as part of our CI (#210). There has been much work by @agilarity on improving CI on the examples, including testing.

**Comment by martinfrances107** [comment]
I have to say I really like this project, and this issues is well structure, I like the delineation of breaking changes.

I just want to introduce a sideways perspective -- "Reasons to walk away from 0.3"

So here is a consumer's story 

When I follow the template step and produce a new  project from leptos version "0.3" and check the projection into github repository employing dependabot 

 I get security warnings  [Ouroboros is Unsound ](https://github.com/martinfrances107/photo_indexer/security/dependabot/1)

Here is my analysis or the situation 

when I ask 

cargo why ouroboros 

I see "leptos_reative" is the only thing pulling in ouroboros

Also this issue was resolved a few says ago with thie PR 

[Replace ouroboros with self_cell](https://github.com/leptos-rs/leptos/pull/1171)

I appreciate managing the pace of releases is not straight forward

To argue against my point -- Some consumers will be put off by the frequent publication of releases with breaking changes,  seeing that incorrectly as sign of instability.

So I am just adding a single factor into a complex decision 

***At some point we must get off 0.3***

------------------------------------------------------------------------
output of cargo why 
```
photo_indexer -> leptos -> leptos_dom -> leptos_reactive -> ouroboros
photo_indexer -> leptos -> leptos_reactive -> ouroboros
photo_indexer -> leptos -> leptos_server -> leptos_reactive -> ouroboros
photo_indexer -> leptos_meta -> leptos -> leptos_dom -> leptos_reactive -> ouroboros
photo_indexer -> leptos_meta -> leptos -> leptos_reactive -> ouroboros
photo_indexer -> leptos_meta -> leptos -> leptos_server -> leptos_reactive -> ouroboros
photo_indexer -> leptos_router -> leptos -> leptos_dom -> leptos_reactive -> ouroboros
photo_indexer -> leptos_router -> leptos -> leptos_reactive -> ouroboros
photo_indexer -> leptos_router -> leptos -> leptos_server -> leptos_reactive -> ouroboros
```

**Comment by nomorechokedboy** [comment]
> * Adding end-to-end testing for examples as part of our CI (

I saw that some of the examples still doesn't have the end-to-end testing, can I write e2e test for them?

**Comment by gbj** [comment]
> > * Adding end-to-end testing for examples as part of our CI (
> 
> I saw that some of the examples still doesn't have the end-to-end testing, can I write e2e test for them?

That would be really, really great.

**Comment by agilarity** [comment]
> > > * Adding end-to-end testing for examples as part of our CI (
> > 
> > 
> > I saw that some of the examples still doesn't have the end-to-end testing, can I write e2e test for them?
> 
> That would be really, really great.

I am adding e2e tests for the `counters_stable` example. The PR will include more `cargo make` tasks to support `trunk` and `playwright`.

**Comment by dezren39** [comment]
> Exploring partial hydration/server components/islands architectures that would allow us to reduce the amount of WASM shipped to the client and increase the ergonomics of loading server-only async data
this would be very cool +1 for anything along this theme, especially isolated islands.

**Comment by gbj** [comment]
> this would be very cool. +1 for anything along this theme, especially isolated islands.

@dezren39 This is very much a WIP demo but you can see the fruits of #1422 at https://leptos-hackernews-islands.fly.dev/

(This does not work on Safari or iOS at the moment; I didn't realize Safari doesn't have `requestIdleCallback`.)

**Comment by Nyabinary** [comment]
Some HTMX-like features would be very cool tbh

**Comment by gbj** [comment]
> Some HTMX-like features would be very cool tbh

Which HTMX-like features are you looking for, how have you tried to use Leptos to achieve the same things, and what's gone wrong?
