### ISSUE TITLE
fix(counters_stable): restore wasm tests

### ISSUE THREAD

**Issue by agilarity** [leptos-rs/leptos#1581]
_Please assign this to me._

## Problem

The wasm tests were deleted by mistake.

## Solution

Restore the wasm tests.

## Tasks

- [x] Restore files
- [x] Fix compile issues (re: cx scope change)
- [x] Fix test failures
  - [x] web::remove_counter::should_decrement_the_number_of_counters
  - [x] web::view_counters::should_see_the_title
  - [x] web::increment_counter::should_increase_the_total_count
  - [x] web::decrement_counter::should_decrease_the_total_count
  - [x] web::enter_count::should_decrease_the_total_count
  - [x] web::enter_count::should_increase_the_total_count
