### ISSUE TITLE
build(examples): make it easier to run examples

### ISSUE THREAD

**Issue by agilarity** [leptos-rs/leptos#1679]
# Start each web example with `cargo-make`

Only examples with web tests currently use `cargo-make` to start the example. The custom tasks automate the installation of `cargo` dependencies and hide implementation details of running an example. This issue aims to extend that support to all web examples.

## Tasks

- [x] Run client examples with `cargo-make`
- [x] Run client/server examples with `cargo-make`
- [x] Update run instructions to reflect the use of `cargo-make` 

_Please assign this issue to me._
