### ISSUE TITLE
0.7 todos

### ISSUE THREAD

**Issue by gbj** [leptos-rs/leptos#2771]
I have merged the `leptos_0.7` branch from #2607 because it is much easier just to juggle main + PRs than main, a branch, PRs to main, and PRs to the branch!

Good first issues/PRs super welcome to fill in missing things:
- [x] `Resource::map` and `Resource::and_then` (use 0.6 as baseline, should be very similar)
- [x] Add in missing deprecated functions for things like `create_blocking_resource` and so on (or at least help compile a list of renamed functions that we can add deprecations for)

Outstanding feature TODOs, in order of priority
- [x] Equivalent to a user implementing `IntoView` on an arbitrary struct (`IntoRender`)
- [x] hot reloading (and therefore view markers)
- [x] `Resource::refetch()`
- [x] static routes
- [x] `Resource::once` (with a relatively more efficient implementation)
- [x] `Await` component (use `Resource::once` above)
- [x] `AnimatedShow`
- [x] Router/Route `base`
- [x] Nested router `set_is_routing`
- [x] `SsrMode::PartiallyBlocked`
- [ ] Figuring out the interaction between `Lazy` routes and hydration (what do you do while hydrating if the code for the route hasn't been lazy-loaded yet?)
- [ ] Reactive channel implementation for single-use signals
- [x] trailing slash modes
- [ ] fallible hydration => start from suspense boundary
- [x] `AnimatedRoutes`/`AnimatedOutlet`

Forward-ported bug fixes (things that have been fixed on 0.6 but reimplemented in 0.7, and need to be checked)
- [x] pending action dispatches (#2653)
- [x] unescaping during navigation (#2651)
- [x] ownership and disposal fixes and tests (#2639)
- [x] ToChildren docs (#2643)
- [x] #2621

Finalizing: 
- [x] simplify tachys APIs by removing duplicated content (HTML length, checking on template duplication, etc.) 
- [ ] reading through docs to make sure they're consistent now

When ready for release
- [x] updating book
- [x] updating sandboxes
- [x] making sure all docsrs docs build and are complete
- [ ] migrating templates to use the new versions of the templates

**Comment by dmgolembiowski** [comment]
> - [ ] Figuring out the interaction between Lazy routes and hydration (what do you do while hydrating if the code for the route hasn't been lazy-loaded yet?)

@gbj Regarding this I was wondering if a [js-sys generated binding](https://github.com/rustwasm/wasm-bindgen/blob/3dc8c29c5c926e42b3b4d2b500e468890a2c5e17/crates/js-sys/src/lib.rs#L4367) to either of [`WebAssembly.compileStreaming()`](https://developer.mozilla.org/en-US/docs/WebAssembly/JavaScript_interface/compileStreaming_static) or [`WebAssembly.instantiateStreaming()`](https://developer.mozilla.org/en-US/docs/WebAssembly/JavaScript_interface/instantiateStreaming_static) could provide the hydration opportunity for a thing that hasn't been loaded yet?

For context:

> _The [`WebAssembly.instantiateStreaming()`](https://github.com/rustwasm/wasm-bindgen/blob/3dc8c29c5c926e42b3b4d2b500e468890a2c5e17/crates/js-sys/src/lib.rs#L4390) static method compiles and instantiates a [`WebAssembly` module](https://github.com/rustwasm/wasm-bindgen/blob/3dc8c29c5c926e42b3b4d2b500e468890a2c5e17/crates/js-sys/src/lib.rs#L4367) directly from a streamed underlying source. This is the most efficient, optimized way to load Wasm code._

I have a suspicion its [`importObject`](https://developer.mozilla.org/en-US/docs/WebAssembly/JavaScript_interface/instantiateStreaming_static#importobject) argument could be the collection of imports for which there is a separate `leptos_lazy_{$sha}.wasm` file corresponding to the DOM's expectation - like a collection of small polyfill files.
